
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int COMA = 12;
  public static final int VER = 9;
  public static final int FINALIZAR = 8;
  public static final int ELIMINAR = 5;
  public static final int PARENTESIS_IZQ = 10;
  public static final int INSERTAR = 4;
  public static final int PARENTESIS_DER = 11;
  public static final int EOF = 0;
  public static final int NUMERO = 16;
  public static final int CREAR = 3;
  public static final int IGUAL = 13;
  public static final int error = 1;
  public static final int DATO = 6;
  public static final int ASIGNAR = 7;
  public static final int PARTIR = 2;
  public static final int ID_VALOR = 15;
  public static final int IDENTIFICADOR = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARTIR",
  "CREAR",
  "INSERTAR",
  "ELIMINAR",
  "DATO",
  "ASIGNAR",
  "FINALIZAR",
  "VER",
  "PARENTESIS_IZQ",
  "PARENTESIS_DER",
  "COMA",
  "IGUAL",
  "IDENTIFICADOR",
  "ID_VALOR",
  "NUMERO"
  };
}

